### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by boberski666** [joanrieu/gst-live#2] opened 2019-02-12 23:25 UTC
When I try to run script I get:

```
root@h-y:/home/obs/gst-live# cat config.sh | ./streamer.sh
0:00:00.039237698  3037      0x16ec590 WARN     GST_ELEMENT_FACTORY gstelementfactory.c:456:gst_element_factory_make: no such element factory "rtmpsink"!
0:00:00.039565427  3037      0x16ec590 ERROR           GST_PIPELINE grammar.y:816:priv_gst_parse_yyparse: no element "rtmpsink"
0:00:00.039818533  3037      0x16ec590 ERROR           GST_PIPELINE grammar.y:901:priv_gst_parse_yyparse: link has no sink [source=@0x16e04a0]
```

**Comment by joanrieu** [comment] 2019-02-13 07:05
You apparently don't have the `rtmpsink` plugin, make sure the `gst-plugins-bad` package is installed on your system (the exact name of the package can vary depending on your distribution).

Closing this issue for now, reopen if the issue isn't solved.

**Comment by boberski666** [comment] 2019-02-13 07:36
I have it installed:

```
root@h-y:~# apt-get install gstreamer1.0-plugins-bad
Reading package lists... Done
Building dependency tree
Reading state information... Done
gstreamer1.0-plugins-bad is already the newest version (1.8.3-1ubuntu0.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by boberski666** [comment] 2019-02-13 07:38
I can only reopen issue I have closed :)

**Comment by joanrieu** [comment] 2019-02-13 07:50
Can you try running the example from the [gstreamer docs](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-bad/html/gst-plugins-bad-plugins-rtmpsink.html) and check if it works or if the same error appears?

EDIT: it won't "work" work, since the URL in the example is only an example, but it should not produce a "no rtmpsink element" kind of error.

**Comment by boberski666** [comment] 2019-02-13 10:35
```
root@h-y:~# gst-launch-1.0 -v videotestsrc ! ffenc_flv ! flvmux ! rtmpsink location='rtmp://localhost/path/to/stream live=1'
WARNING: erroneous pipeline: no element "ffenc_flv"
root@h-y:~# gst-launch-1.0 -v videotestsrc ! flvmux ! rtmpsink location='rtmp://localhost/path/to/stream live=1'
WARNING: erroneous pipeline: no element "rtmpsink"
root@h-y:~#
```

Noooo error is the same :(

**Comment by joanrieu** [comment] 2019-02-13 21:45
It looked you were running ubuntu so I've just checked the contents of the [`gstreamer1.0-plugins-bad`](https://packages.ubuntu.com/cosmic/amd64/gstreamer1.0-plugins-bad/filelist) package and it's supposed to contain this file: `/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstrtmp.so` which provides the RTMP sink.

If you don't have this file on your system, your GStreamer installation is probably broken, I'd suggest reinstalling the related packages.

**Closed as completed by joanrieu** 2019-02-13 21:45 UTC

**Comment by boberski666** [comment] 2019-02-13 22:04
And what about if I have that file?

**Comment by joanrieu** [comment] 2019-02-13 22:16
Well, it should work then... 🤔 

Try poking around with [`gst-inspect-1.0`](https://gstreamer.freedesktop.org/documentation/tools/gst-inspect.html) to find the broken part of your setup.

```
$ gst-inspect-1.0 rtmp
$ gst-inspect-1.0 rtmpsink
```

If it doesn't find anything, try adding the `--gst-plugin-path=/usr/lib/x86_64-linux-gnu/gstreamer-1.0` flag just in case.

If nothing comes out, you can also try to dump all the plugins (it should also output errors for plugins it finds but fails to load):
```
$ gst-inspect-1.0 --print-all --gst-plugin-spew
```
Be careful with that one, the output might be huge.

**Comment by leaf918** [comment] 2020-08-20 08:43
Maybe. it should use the latest version of video plugin,like this:
gst-launch-1.0 -v videotestsrc is_live=true ! avenc_flv ! avmux_flv ! rtmpsink location='rtmp://localhost:8888/path/to/stream live=1'
